apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:latest
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "LocalExecutor"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow"
            - name: _AIRFLOW_WWW_USER_CREATE
              value: "true"
            - name: _AIRFLOW_WWW_USER_USERNAME
              value: "admin"
            - name: _AIRFLOW_WWW_USER_PASSWORD
              value: "admin"
            - name: _AIRFLOW_WWW_USER_EMAIL
              value: "admin@example.com"
            - name: _AIRFLOW_WWW_USER_ROLE
              value: "Admin"
            - name: _AIRFLOW_WWW_USER_FIRSTNAME
              value: "John"
            - name: _AIRFLOW_WWW_USER_LASTNAME
              value: "Doe"
          ports:
            - containerPort: 8082
          command: ["bash", "-c"]
          args:
            - |
              airflow db upgrade
              airflow users create --username admin --password admin --firstname John --lastname Doe --role Admin --email admin@example.com || true
              exec airflow webserver --port 8082 &
              exec airflow scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
